### ISSUE TITLE
cli: create workflow without REANA_SERVER_URL set output

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-client#149] opened 2018-08-07 12:49 UTC
When there is no REANA_SERVER_URL set and a user tries to create a workflow, currently this is the output:
```
(reana-3.6) ➜  reana-demo-alice-lego-train-test-run git:(master) rc create
Workflow could not be created: 

```
We should show a message mentioning the environment var.

**Comment by diegodelemos** [comment] 2018-08-10 07:12
Couldn't reproduce this with Python2.7 nor Python3.6. I have tried with no `REANA_SERVER_URL`, and also not `REANA_ACCESS_TOKEN`. If you can not reproduce it anymore, lets close it.

P.S. There is small chance that [this PR](https://github.com/reanahub/reana-client/pull/154) affected.

**Closed** 2018-08-10 14:39 UTC
Labels: Status: in work
