### ISSUE TITLE
cli: verify stop functionality

### ISSUE THREAD

**Issue by tiborsimko** [reanahub/reana-client#240] opened 2019-01-28 17:57 UTC
Seen a case when a workflow run couldn't be stopped:

```console
$ reana-client status -w bsm-user-7.1 
NAME         RUN_NUMBER   CREATED               STATUS    PROGRESS
bsm-user-7   1            2019-01-28T16:48:34   running   15/65  
$ reana-client stop -w bsm-user-7.1  --force
Workflow could not be stopped: 
(404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 28 Jan 2019 17:54:55 GMT', 'Content-Length': '262'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"jobs.batch \"feef41e0-3bf2-48f6-99b0-13540ac18b09\" not found","reason":"NotFound","details":{"name":"feef41e0-3bf2-48f6-99b0-13540ac18b09","group":"batch","kind":"jobs"},"code":404}
```

We should verify the functionality.

**Comment by diegodelemos** [comment] 2019-10-04 14:16
Closing as duplicate of https://github.com/reanahub/reana-client/issues/314 and fixed in https://github.com/reanahub/reana-workflow-controller/pull/250.

**Closed by diegodelemos** 2019-10-04 14:16 UTC
