### ISSUE TITLE
cli: modify existing parameters when starting workflow

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-client#152] opened 2018-08-08 14:48 UTC
Stemmed from https://github.com/reanahub/reana-client/pull/151#discussion_r208607561,  we could implement a new feature where we could allow users to modify parameters of a workflow already created:
```console
# A user creates a workflow from his current `reana.yaml` and inside this call
# some input parameters are passed, such as `num_events=20`.
~/reana-analysis $ reana-client create
workflow.1 has been started.
~/reana-analysis $ export REANA_WORKON=workflow.1
~/reana-analysis $ reana-client upload data/*
# Now, the user wants to execute this workflow but with different number of events.
~/reana-analysis $ reana-client start -p num_events=2000
```

**Comment by mdonadoni** [comment] 2024-06-18 12:59
As far as I can tell, this is a duplicate of https://github.com/reanahub/reana-client/issues/200

**Closed by mdonadoni** 2024-06-18 12:59 UTC
Labels: type/feature, cli/general
